variables:
  PHP_CONTAINER_URI: "registry.concept7.nl/workflow/php-${PHP_VERSION}:latest"

.install-composer:
  before_script:
    - php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

.composer-install:
  before_script:
    - !reference [.install-composer, before_script]
    - composer install --prefer-dist --no-interaction --no-progress

stages:
  - test

pint:
  stage: test
  image: "registry.concept7.nl/workflow/php-8.4:latest"
  extends: .composer-install
  script:
    - vendor/bin/pint --test

pest:
  stage: test
  image: $PHP_CONTAINER_URI
  extends: .composer-install
  parallel:
    matrix:
      - PHP_VERSION: "8.2"
      - PHP_VERSION: "8.3"
  script:
    - vendor/bin/pest

pest:coverage:
  stage: test
  image: "registry.concept7.nl/workflow/php-8.4:latest"
  extends: .composer-install
  script:
    - vendor/bin/pest --colors=never --log-junit=phpunit-report.xml --coverage --coverage-cobertura=coverage.cobertura.xml
  artifacts:
    paths:
      - phpunit-report.xml
      - coverage.cobertura.xml
    reports:
      junit: phpunit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml
  coverage: '/Total:\s+\d+\.\d+ %/'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED
